apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: hybrid-cloud-demo

# Adds hybrid-cloud-demo label to all resources.
commonLabels:
  app.kubernetes.io/part-of: hybrid-cloud-demo

resources:
  - cloud-identifer-task.yaml
  - openshift-cli-deploy-task.yaml
  - skupper-site-task.yaml
  - ksvc-deploy.yaml
  - svc-deploy.yaml
  - skupper-site-deploy.yaml
