apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skupper-site
spec:
  description: >-
    Create Skupper site based on https://github.com/skupperproject/skupper/tree/0.3/cmd/site-controller
  params:
    - name: SITE_NAME
      description: The Skupper VAN Site name
      default: skupper
    - name: CLUSTER_LOCAL
      description: >-
        Set up skupper to only accept connections from within the local cluster.
      default: "false"
    - name: CONSOLE
      description: >-
        Enable skupper console.
      default: "true"
    - name: CONSOLE_AUTHENTICATION
      description: >-
        The authentication method for skupper console, possible values are: openshift or internal or unsecured
      default: "openshift"
    - name: CONSOLE_USER
      description: >-
        The console login user for internal option
      default: "skupper"
    - name: CONSOLE_PASSWORD
      description: >-
        The console login user password for internal option
      default: "skupper"
    - name: EDGE
      description: >-
        Set up an edge skupper site.
      default: "false"
    - name: ROUTER_CONSOLE
      description: >-
        Set up a Dispatch Router console (not recommended).
      default: "false"
    - name: SERVICE_CONTROLLER
      description: >-
        Run the service controller.
      default: "true"
    - name: SERVICE_SYNC
      description: >-
        Only relevant if the service controller is running. Determine if the service controller participates in service synchronization.
      default: "true"
  steps:
    - name: deploy-skupper-site
      image: quay.io/rhdevelopers/origin-cli-yq-jq
      script: "oc $@"
      args:
        - create
        - cm
        - skupper-site
        - "--from-literal=cluster-local=$(params.CLUSTER_LOCAL)"
        - "--from-literal=console=$(params.CONSOLE)"
        - "--from-literal=console-authentication=$(params.CONSOLE_AUTHENTICATION)"
        - "--from-literal=console-password=$(params.CONSOLE_PASSWORD)"
        - "--from-literal=console-user=$(params.CONSOLE_USER)"
        - "--from-literal=edge=$(params.EDGE)"
        - "--from-literal=name=$(params.SITE_NAME)"
        - "--from-literal=router-console=$(params.ROUTER_CONSOLE)"
        - "--from-literal=service-controller=$(params.SERVICE_CONTROLLER)"
        - "--from-literal=service-sync=$(params.SERVICE_SYNC)"
