---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app.kubernetes.io/part-of: hybrid-cloud-demo
    app.kubernetes.io/name: hybrid-cloud-backend
  name: "hybrid-cloud-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hybrid-cloud-frontend
  template:
    metadata:
      labels:
        app: hybrid-cloud-frontend
    spec:
      containers:
        - env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
          image: "<will be replaced by deploment>"
          imagePullPolicy: "IfNotPresent"
          name: "hybrid-cloud-frontend"
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          resources:
            limits:
              memory: "1200Mi"
              cpu: "750m"
            requests:
              memory: "500Mi"
              cpu: "500m"
