---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ksvc-deploy-run-
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    tekton.dev/pipeline: ksvc-deploy
spec:
  params:
    - name: APP_NAME
      value: hybrid-cloud-backend
    - name: KN_MAX_SCALE
      value: "1"
    - name: SERVICE_TIER
      value: backend
    - name: GITHUB_REPO_URL
      value: $(ARGOCD_APP_SOURCE_REPO_URL)
    - name: GITHUB_REPO_REVISION
      value: $(ARGOCD_APP_SOURCE_TARGET_REVISION)
  pipelineRef:
    name: ksvc-deploy
  serviceAccountName: hybrid-cloud-demo-sa
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: hybrid-cloud-demo-sources
    - configMap:
        name: maven-settings
      name: maven-settings
