---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-cloud-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: WORKER_CLOUD_ID
              value: gcp
