apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: skupper-site
    behavior: create
    literals:
      - cluster-local="false"
      - console="true"
      - console-authentication="openshift"
      - console-password="bugs"
      - console-user="bunny"
      - edge="false"
      - name=hybrid-cloud-aws
      - router-console="true"
      - service-controller="true"
      - service-sync="true"
bases:
  - ../base
