apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
spec:
  destination:
    namespace: hybrid-cloud-demo
    server: "https://kubernetes.default.svc"
  source:
    path: k8s/core
    repoURL: "http://gogs.192.168.39.197.nip.io/gogs/hybrid-cloud"
    targetRevision: knative
  project: hybrid-cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
