apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hybrid-cloud-skupper
spec:
  destination:
    namespace: hybrid-cloud-demo
    server: "https://kubernetes.default.svc"
  source:
    path: k8s/skupper
    repoURL: "https://github.com/redhat-developer-demos/hybrid-cloud"
    targetRevision: master
    kustomize:
      images:
        - "quay.io/skupper/site-controller:0.3"
  project: hybrid-cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
