apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
spec:
  destination:
    namespace: hybrid-cloud-demo
    server: "https://kubernetes.default.svc"
  source:
    path: k8s/rbac
    repoURL: "http://github.com/redhat-developer-demos/hybrid-cloud"
    targetRevision: knative
  project: hybrid-cloud
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
