apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skupper
spec:
  destination:
    namespace: hybrid-cloud-demo
    server: "https://kubernetes.default.svc"
  source:
    path: k8s/skupper
    repoURL: "http://gogs.192.168.39.197.nip.io/gogs/hybrid-cloud"
    targetRevision: knative
    kustomize:
      images:
        - "quay.io/skupper/site-controller:0.3"
  project: hybrid-cloud
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
