project: hybrid-cloud
source:
  repoURL: "http://gogs.192.168.39.197.nip.io/gogs/hybrid-cloud"
  path: k8s/core
  targetRevision: knative
destination:
  server: "https://kubernetes.default.svc"
  namespace: hybrid-cloud-demo
syncPolicy:
  automated:
    automated:
      prune: false
      selfHeal: false
