---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hybrid-cloud-frontend
  name: hybrid-cloud-frontend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: hybrid-cloud-frontend
  type: LoadBalancer
