---
apiVersion: v1
kind: Secret
metadata:
  # only allow 5 outstanding requests, before spillover
  # annotations:
  #   skupper.io/cost: "5"
  labels:
    skupper.io/type: connection-token-request
  name: site-token
