- name: Serverless with OpenShift Pipelines and Argo CD
  hosts: localhost
  connection: local

  vars:
    ocp_version: 4.5.6
    download_clients: False
    deploy_serverless: True
    deploy_pipelines: True
    deploy_argocd: True
    argocd_namespace: argocd
    users:
      create: True
      start: 0
      end: 0
      prefix: user
    argocd_manifests_dir: argocd

  environment:
    K8S_AUTH_KUBECONFIG: '{{ kubeconfig }}'

  roles:
    - kameshsampath.openshift_app_spices

- import_playbook: add_tasks.yml