- name: "Hybrid Cloud Demo::Configure, Setup and Deploy"
  hosts: all
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    install_operators: False
    ocp_version: 4.5.6
    download_clients: False
    deploy_serverless: True
    deploy_pipelines: True
    deploy_argocd: True
    argocd_namespace: argocd
    users:
      create: True
      start: 0
      end: 0
      prefix: user
    argocd_manifests_dir: argocd

  tasks:
    - name: Log in (obtain access token)
      community.kubernetes.k8s_auth:
        username: admin
        password: "{{ k8s_admin_password }}"
      register: k8s_auth_results

  roles:
    - role: kameshsampath.openshift_app_spices
      environment:
        K8S_AUTH_HOST: '{{ api_server }}'
        K8S_AUTH_API_KEY: '{{ k8s_auth_results.k8s_auth.api_key }}'    
      when: install_operators
    - role: hybrid_cloud_demo
      environment:
        K8S_AUTH_HOST: '{{ api_server }}'
        K8S_AUTH_API_KEY: '{{ k8s_auth_results.k8s_auth.api_key }}'