name: backend

on:
  push:
    branches: 
    - master
    paths:
    - backend/**
    - .github/workflows/backend-action.yml

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    env:
      working-directory: backend
    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - name: Maven Build
      run: ./mvnw package
